app:
  image: quay.io/testobject/app:1.0.17
  links:
    - testobject-mongo:mongo
  extends:
     file: ../base.yml
     service: app
  environment:
    - env.host.name=
    - web.baseurl=http://
    - appium.baseurl=http://
  volumes:
    - cloud.resources.disabled=false
    # The below volume should be uncommented if you are using self signed certificates
    # /root/trusted-certificates should be a directory on the app host
    # containing self-signed ssl certificates, file extension .cer
    # - /root/trusted-certificates:/root/.testobject/trusted-certificates

monitoring:
  image: quay.io/testobject/monitoring:1.0.17
  links:
    - testobject-mongo:mongo
  extends:
    file: ../base.yml
    service: monitoring

testobject-mongo:
  image: mongo:3.0.6
  extends:
    file: ../base.yml
    service: testobject-mongo
