testobject-android-sdk:
  image: quay.io/testobject/android-sdk-linux
  container_name: "testobject-android-sdk"

appium-1.4.10:
  image: quay.io/testobject/appium:1.4.10
  container_name: "appium-1.4.10"
  volumes: /root/appium/appium/1.4.10

testobject-mongo:
  image: mongo:3.1.9
  extends:
    file: base.yml
    service: testobject-mongo

app:
  image: quay.io/testobject/app:1.0.17
  links:
    - testobject-mongo:mongo
  extends:
     file: base.yml
     service: app
  environment:
    - env.host.name=
    - web.baseurl=http://

monitoring:
  image: quay.io/testobject/monitoring:1.0.17
  links:
    - testobject-mongo:mongo
  extends:
    file: base.yml
    service: monitoring


ios-pool:
  image: quay.io/testobject/pool:1.0.17
  extends:
    file: base.yml
    service: ios
  volumes_from:
    - appium-1.4.10
  environment:
    - server.id=pool-ios-1
    - env.host.name=

android-pool:
  image: quay.io/testobject/pool:1.0.17
  extends:
    file: base.yml
    service: android
  volumes_from:
    - appium-1.4.10
    - testobject-android-sdk
  environment:
    - device.pool.vmlite.license=
    - env.host.name=
    - server.id=pool-android-1
