testobject-android-sdk:
  image: quay.io/testobject/android-sdk-linux
  container_name: "testobject-android-sdk"
  volumes:
      - /opt/android-sdk-linux

appium-1.4.10:
  image: quay.io/testobject/appium:1.4.10
  container_name: "appium-1.4.10"
  volumes:
    - /root/appium/appium/1.4.10

appium-1.5.2:
  image: quay.io/testobject/appium:1.5.2
  container_name: "appium-1.5.2"
  volumes:
    - /root/appium/appium/1.5.2

testobject-mongo:
  image: mongo:3.1.9
  extends:
    file: base.yml
    service: testobject-mongo

app:
  image: quay.io/testobject/app:1.0.17
  links:
    - testobject-mongo:mongo
  extends:
     file: base.yml
     service: app
  environment:
    - env.host.name=
    - web.baseurl=http://
    - appium.baseurl=http://
    - cloud.resources.disabled=false
    # The below values can be left empty
    - github.issues.oauth.client.id=
    - github.issues.oauth.client.secret=
    - github.login.oauth.client.id=
    - github.login.oauth.client.secret=
    - google.login.oauth.client.id=
    - google.login.oauth.client.secret=
    - linkedin.login.oauth.client.id=
    - linkedin.login.oauth.client.secret=
  volumes:
    # The below volume should be uncommented if you are using self signed certificates
    # /root/trusted-certificates should be a directory on the app host
    # containing self-signed ssl certificates, file extension .cer
    # - /root/trusted-certificates:/root/.testobject/trusted-certificates

monitoring:
  image: quay.io/testobject/monitoring:1.0.17
  links:
    - testobject-mongo:mongo
  extends:
    file: base.yml
    service: monitoring


ios-pool:
  image: quay.io/testobject/pool:1.0.17
  extends:
    file: base.yml
    service: ios
  volumes_from:
    - appium-1.4.10
    - appium-1.5.2
  environment:
    - server.id=pool-ios-1
    - env.host.name=
    # Prevent auto-dimming of device screens
    # - device.pool.brightness=100

android-pool:
  image: quay.io/testobject/pool:1.0.17
  extends:
    file: base.yml
    service: android
  volumes_from:
    - appium-1.4.10
    - appium-1.5.2
    - testobject-android-sdk
  environment:
    - device.pool.vmlite.license=
    - env.host.name=
    - server.id=pool-android-1
    # Prevent auto-dimming of device screens
    # - device.pool.brightness=100
