testobject-android-sdk:
  image: quay.io/testobject/android-sdk-linux
  container_name: "testobject-android-sdk"
  volumes:
      - /opt/android-sdk-linux
      
appium-1.4.10:
  image: quay.io/testobject/appium:1.4.10
  container_name: "appium-1.4.10"
  volumes:
    - /root/appium/appium/1.4.10

appium-1.5.2:
  image: quay.io/testobject/appium:1.5.2
  container_name: "appium-1.5.2"
  volumes:
    - /root/appium/appium/1.5.2

ios-pool:
  image: quay.io/testobject/pool:1.0.17
  extends:
    file: ../base.yml
    service: ios
  volumes_from:
    - appium-1.4.10
    - appium-1.5.2
  environment:
    - server.id=pool-ios-1
    - env.host.name=
    # Prevent auto-dimming of device screens
    # - device.pool.brightness=100

android-pool:
  image: quay.io/testobject/pool:1.0.17
  extends:
    file: ../base.yml
    service: android
  volumes_from:
    - appium-1.4.10
    - appium-1.5.2
    - testobject-android-sdk
  environment:
    - device.pool.vmlite.license=
    - env.host.name=
    - server.id=pool-android-1
    # Prevent auto-dimming of device screens
    # - device.pool.brightness=100
